services:
  postgres:
    image: postgres:latest
    container_name: void-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - voidcontests

  redis:
    image: redis:latest
    container_name: void-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli PING
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - voidcontests

volumes:
  postgres_data:
  redis_data:

networks:
  voidcontests:
    name: voidcontests
    driver: bridge
